version: '2'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      # - '${API_SOURCE_PATH}:/app' # default docker volume sync
      # - '${API_SOURCE_PATH}:/app:cached' # docker caching layer
      - app-sync:/app:nocopy # macOS: docker-sync
    ports:
      - '${API_WEB_PORT}:80'
    depends_on:
      - api

  api:
    build:
      context: ./api
    volumes:
      # - '${API_SOURCE_PATH}:/app' # default docker volume sync
      # - '${API_SOURCE_PATH}:/app:cached' # docker caching layer
      - app-sync:/app:nocopy # macOS: docker-sync

  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foobar
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo

# macOS: for docker-sync
volumes:
  app-sync:
    external: true
  mysql:
